/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pado_jni_JNI */

#ifndef _Included_com_pado_jni_JNI
#define _Included_com_pado_jni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pado_jni_JNI
 * Method:    start
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pado_jni_JNI_start
  (JNIEnv * env, jobject, jint);

/*
 * Class:     com_pado_jni_JNI
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pado_jni_JNI_stop
  (JNIEnv * env, jobject);

JNIEXPORT jstring JNICALL Java_com_pado_jni_JNI_call
(JNIEnv* env, jobject obj, jstring param);
#ifdef __cplusplus
}
#endif
#endif
